todooproject/todooapp/urls.py
from django.urls import path

from . import views

app_name = 'todooapp'


urlpatterns = [
    path('', views.add, name='add'),
    path('delete/<int:taskid>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update')

    ]

todooproject/todooproject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todooapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todooproject/todooapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todooproject/todooapp/views.py
from django.shortcuts import render, redirect

from .form import TodoForm
from .models import Task


# Create your views here.
def add(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date= request.POST.get('date', '')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'index.html',{'task1':task1})

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method =='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html' ,{'f':f,'task':task})

todooproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todooproject/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure this task is done?</p>
    <button type="submit">confirm</button>
</form>

{% endblock %}

todooproject/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

todooproject/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{f.as_p}}

    <button type="submit">confirm</button>
</form>
{% endblock %}

todooproject/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="banner">
            <div class="banner-text">
                <h1>ToDo</h1>
            </div>
        </div>
    </div>
</div>
 <div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
    {% csrf_token %}
            <div class="form-group">
               <input type="text"  class="form-control" name="task" placeholder="taskname"><br>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="priority" placeholder="priority">
            </div>
                <br>
                <div class="form-group">
                <input type="date" class="form-control" name="date" placeholder="enter the date">
            </div><br>
            <input type="submit" class="btn btn-success"  value="submit">
           </form>



         </div>
           <div class="col-md-6">
               <h4>Task to be completed</h4>
                {% for i in task1 %}
               <div class="shadow card">
                   <div class="card-body">
                       <h5 class="card-title">{{i.name}}</h5>
                       <p><b>{{i.priority}}</b></p>
                        <p><b>{{i.date}}</b></p>
                        <a class="btn btn-danger" href="{% url 'todooapp:delete' i.id %}">Done</a>
                         <a class="btn btn-success" href="{% url 'todooapp:update' i.id %} ">Update</a>
                   </div>
               </div>
               <br>
               {% endfor %}
           </div>

    </div>
</div>

{% endblock %}

todooproject/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">confirm</button>
</form>
        </div>
    </div>
</div>


{% endblock %}